name: Run E2E tests
on:
  deployment_status:
jobs:
  first:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: echo 'Running in environment: ${{ github.event.deployment_status.environment }}'
      - env:
          URL: `${{ github.event.deployment_status.environment_url }}`
          API_KEY: `${{ secrets.API_KEY }}`
        run: npm test
